version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/

  build:
    commands:
      - echo "Running Terraform"
      - terraform --version
      - terraform init -input=false
      - terraform plan -out=tfplan -target=aws_vpc.main -target=aws_subnet.public -target=aws_security_group.web_sg -target=aws_instance.web
      - terraform apply -auto-approve tfplan
